### ISSUE TITLE
Set up code coverage tracking?

### ISSUE THREAD

**Issue by fingolfin** [snw-0/sl2-reps#12]
With 11be9985eda463648fb40ec97c1c78ffb008dc70 you have not only activated CI tests (great!) but also set the foundation for tracking code coverage via codecov.io. The only thing missing is to enable this for this repository. I believe the only thing required to do this is to go to https://github.com/apps/codecov and use the "Configure" button to enable it for this repository.

Afterwards code coverage reports will start showing up under https://app.codecov.io/gh/snw-0/sl2-reps whenever a new CI test result is completed.

You can get a preview of how that will look here: https://app.codecov.io/gh/fingolfin/sl2-reps/tree/main

**Comment by fingolfin** [comment]
Just to say, this can be beneficial to find out which parts of your code are not tested and/or not used. E.g. it reveals an unused function `_SL2IrrepsPPLOfMaxDegree` (no calls to it exist in the code), and also functions which are not covered by tests (i.e. there are calls to them in functions that are being tested, just not the code path leading to those function calls, e.g. `_SL2IrrepsPPLOfDegree`, `SL2IrrepsOfDegree`, `SL2IrrepsOfLevel`. The latter could be significant because if there are no tests exercising them, then (a) they might just be broken, or (b) they may work now but a future update to this package or even to GAP may break them, and we won't notice.

**Comment by snw-0** [comment]
Okay, I've got it set up.  I'll look into writing tests for everything.
