### ISSUE TITLE
Make a release?

### ISSUE THREAD

**Issue by fingolfin** [snw-0/sl2-reps#14]
In order to pick this up for the GAP package distribution, a new release is needed. `Status := "deposited"` could also be set

**Comment by snw-0** [comment]
Okay, I've made a v1.1 release and set the status to `deposited`.

**Comment by fingolfin** [comment]
Unfortunately there are several issues with the release tarball, which prevents me from adding it to the package distro. See in particular issues #15, #16 and #17
